name: "Gen App Token"
description: "Generate GitHub app's access token for accessing private repos."
inputs:
  app_private_key:
    description: "RSA Private Key of the GitHub app."
    required: true
  app_id:
    description: "GitHub app's id."
    required: true
  app_install_id:
    description: "GitHub app's install id. If not set, first install is used."
    required: false
outputs:
  access_token:
    description: "GitHub access token."
runs:
  using: "node16"
  main: "dist/index.js"
